// Demo content for pilots and testing (all fictional, removable with the demo
// data in Admin → Agencies). Portfolio photos were generated with Higgsfield
// (GPT Image) and live in data/demo-portfolio/<handle>-<n>.webp.

/** More Saudi agencies, so the multi-country interface can be tried city by city. Prices in SAR a month. */
export const SAUDI_DEMO_AGENCIES = [
  { handle: "riyadh.pulse", name: "Riyadh Pulse", bio: "Google Ads, SEO and bilingual websites for Saudi real estate and professional services. Leads you can count.", city: "riyadh", services: ["ads_google", "seo", "web_design", "analytics"], platforms: ["google", "linkedin"], industries: ["real_estate", "professional_services"], price: 4500, verified: true, founded: 2017, team: "16-40" },
  { handle: "dammam.studio", name: "استوديو الدمام", bio: "تصوير وإنتاج فيديو للمصانع والمطاعم والشركات في المنطقة الشرقية.", city: "dammam", services: ["video_production", "photography", "motion_graphics"], platforms: ["instagram", "youtube", "linkedin"], industries: ["manufacturing", "restaurant_cafe", "professional_services"], price: 3000, verified: true, founded: 2019, team: "6-15" },
  { handle: "khobar.brands", name: "Khobar Brands", bio: "Brand identity, packaging and social content for new Saudi brands, from logo to launch.", city: "khobar", services: ["brand_identity", "packaging_design", "graphic_design", "smm_content"], platforms: ["instagram", "tiktok"], industries: ["restaurant_cafe", "retail_shop", "ecommerce"], price: 3800, verified: false, founded: 2021, team: "2-5" },
  { handle: "makkah.hospitality", name: "ضيافة مكة للتسويق", bio: "إدارة حسابات وإعلانات ميتا وجوجل للفنادق وشركات العمرة والضيافة في مكة المكرمة.", city: "makkah", services: ["smm_management", "ads_meta", "ads_google"], platforms: ["instagram", "facebook", "google"], industries: ["tourism_hospitality"], price: 3200, verified: true, founded: 2016, team: "6-15" },
  { handle: "abha.trails", name: "Abha Trails Media", bio: "Tourism films, drone and photo stories from Asir's mountains for hotels, tours and destinations.", city: "abha", services: ["video_production", "photography", "smm_content"], platforms: ["instagram", "youtube", "tiktok"], industries: ["tourism_hospitality"], price: 2800, verified: false, founded: 2022, team: "2-5" },
  { handle: "madinah.dates", name: "تمور المدينة ديجيتال", bio: "إطلاق المتاجر الإلكترونية للتمور والهدايا: تصوير منتجات وإعلانات سناب شات وتيك توك.", city: "madinah", services: ["ecommerce_setup", "ads_snapchat", "ads_tiktok", "photography"], platforms: ["snapchat", "tiktok", "instagram"], industries: ["ecommerce", "retail_shop"], price: 2500, verified: true, founded: 2020, team: "2-5" },
];

/** One caption per portfolio photo (data/demo-portfolio/<handle>-<n>.webp), in the agency's own language. */
export const PORTFOLIO_CAPTIONS: Record<string, string[]> = {
  "nakhla.studio": ["جلسة تصوير قائمة الإفطار لمقهى في جبل عمّان: قهوة مختصة وكنافة وكرواسون بإضاءة طبيعية.", "خلف الكواليس: تصوير ريلز لفن اللاتيه مع باريستا المقهى بهاتف وجيمبال.", "هوية موحّدة لحساب مطعم على إنستغرام: شبكة منشورات متناسقة للأطباق والمكان."],
  "petra.growth": ["Performance dashboard for an e-commerce client: revenue up month after month from Meta and TikTok ads.", "UGC-style skincare unboxing ad for Meta. Best-performing creative of the quarter.", "Sneaker drop on TikTok: vertical product videos tested against the analytics every week."],
  "sahel.media": ["تصوير استقبال عيادة في إربد لحساباتها على السوشيال ميديا: مكان نظيف ومريح للمرضى.", "محتوى يقدّمه الطبيب: طبيب أسنان يشرح للمريض خطوات العلاج بلغة بسيطة.", "حملة توعية صحية: منشورات بألوان العيادة وحساب إنستغرام متجدد."],
  "aqaba.waves": ["Drone shot of the Aqaba coastline for a Red Sea resort's summer campaign.", "Underwater series over the coral reef for a diving centre. Shot on location in Aqaba.", "Behind the scenes: filming a sunset boat trip for a hospitality campaign."],
  "zaytoon.brand": ["هوية بصرية كاملة لعلامة ناشئة: شعار وبطاقات وورق رسمي ولوحة ألوان بالزيتوني والكريمي.", "دليل الهوية: الخطوط والألوان وطريقة استخدام الشعار في كل مكان.", "تصميم تغليف لزيت زيتون حرفي: زجاجات وعلب كرافت بشعار هندسي بسيط."],
  "reel.house.jo": ["UGC shoot with a creator for a beauty brand: vertical video, ring light, one take energy.", "Three reels, three brands, one week. Short-form content for food and beauty clients.", "Behind the scenes of a TikTok trend shoot in the streets of Amman."],
  "zarqa.digital": ["تصوير واجهة محل أدوات منزلية في الزرقاء لحملة فيسبوك محلية.", "إعلان خصومات لمتجر أجهزة على فيسبوك وإنستغرام: تصميم وإعلان ممول.", "قوالب منشورات ثابتة للمحلات الصغيرة: تصميم مرة واحدة واستخدام طوال الشهر."],
  "linked.levant": ["LinkedIn portraits for a consulting firm's partners, shot in their Amman office.", "B2B seminar coverage: speaker photos and posts for the company's LinkedIn page.", "Company page content plan: thought-leadership posts and ads for professional services."],
  "snap.souq": ["إعلان سناب شات لسماعات جديدة: موديل وخلفية صفراء جريئة وتصوير عمودي.", "تصوير منتجات إكسسوارات لمتجر إلكتروني على خلفية صفراء.", "حملة إطلاق متجر: من الإعلان إلى صفحة الدفع والتوصيل."],
  "salt.stories": ["A photo story from the old town of As-Salt for a heritage and tourism project.", "Documentary coverage of an NGO's school supply drive in a community centre.", "Filming a craftsman in his workshop for a heritage storytelling series."],
  "madaba.pixels": ["تصوير منتجات فسيفساء مادبا اليدوية لمتجر هدايا على إنستغرام.", "جلسة تصوير قائمة مطعم: منسف ومقبلات بتصوير علوي.", "استوديو تصوير منتجات صغير: إضاءة وخلفيات جاهزة للمتاجر والمطاعم."],
  "search.first.jo": ["SEO and Google Ads for a real estate company: organic traffic up for six months straight.", "A fast, responsive website tested on phone, tablet and laptop before launch.", "Listings website for an Amman real estate office, built to rank and convert."],
  "shifa.digital": ["فيديو توعوي يقدّمه طبيب جلدية لعيادته، بتصوير بسيط داخل العيادة.", "محتوى لمركز علاج طبيعي: تمارين الركبة بإشراف المعالج.", "إطلاق خدمة توصيل صيدلية عبر إعلانات ميتا وطلبات واتساب."],
  "najd.creative": ["تصوير طبق مطعم في الرياض لسناب شات بالهاتف والجيمبال.", "محتوى عمودي لصانع محتوى سعودي في بوليفارد الرياض ليلًا.", "تصوير متجر عبايات في الرياض لحساباته على السوشيال ميديا."],
  "jeddah.growth": ["Brand launch event on the Jeddah waterfront: coverage, content and paid social.", "Strategy workshop with a Saudi client team: channels, budget and targets for the year.", "Luxury apartment campaign in Jeddah: listing photos and lead ads."],
  "dubai.loop": ["Rooftop pool at sunset for a Dubai hotel's summer campaign.", "Chef's table film for a Dubai restaurant: plating in the kitchen, shot cinematic.", "Sunrise workout content for a fitness brand on a Dubai beach."],
  "capital.b2b.ae": ["Keynote coverage for a B2B conference in Abu Dhabi.", "Whitepaper launch and LinkedIn campaign for an Abu Dhabi consultancy.", "Executive portrait session for a thought-leadership series on LinkedIn."],
  "gulf.pixel.kw": ["تصوير عطور فاخرة على سطح عاكس لمتجر كويتي.", "تصوير حلويات مقهى في الكويت: كيكة فستق وقهوة عربية وتمر.", "افتتاح مطعم برغر في مدينة الكويت: محتوى سناب شات من يوم الافتتاح."],
  "doha.frame": ["Gala dinner coverage for a Doha venue: video and photos for social media.", "Doha skyline at blue hour for a tourism video.", "Graduation day coverage for a university in Qatar."],
  "manama.social": ["تصوير بوتيك في المنامة لحسابه على إنستغرام.", "تصميم إعلانات ميتا لشركة صغيرة في البحرين مع معاينة على الهاتف.", "تصوير عيادة أسنان في البحرين لصفحتها على فيسبوك."],
  "muscat.media": ["قرى الجبل الأخضر عند الشروق لحملة سياحية في عُمان.", "منتجع على شاطئ مسقط بعمارة عُمانية تقليدية لحملة ضيافة.", "طبق سمك مشوي لمطعم على البحر في مسقط."],
  "nile.digital": ["هوية بصرية لعلامة أزياء مصرية ناشئة: شعار على الأكياس والبطاقات والعلب.", "اجتماع فريق العمل في القاهرة: لوحات أفكار لحملة جديدة.", "إعلان خارجي لعلامة أثاث منزلي في القاهرة."],
  "alex.reels": ["Reel on the Alexandria corniche for a local brand, shot vertical in one afternoon.", "Beauty creator content for a cosmetics brand: tutorial-style reels.", "Alexandria street food for TikTok: a fish sandwich stand that went viral."],
  "riyadh.pulse": ["Google Ads and SEO results reviewed with a Riyadh real estate client.", "Villa listing photos for a Riyadh developer's lead campaign.", "Bilingual Arabic-English website presented to a Saudi client."],
  "dammam.studio": ["فيلم منتج لمصنع في الدمام: كاميرا سينمائية وإضاءة درامية.", "مطعم مأكولات بحرية على كورنيش الدمام وقت الغروب لإنستغرام.", "صور شخصية احترافية لموظفي شركة في المنطقة الشرقية."],
  "khobar.brands": ["Identity for a specialty coffee roaster in Khobar: cups, bags and signage.", "Arabic calligraphy logo concepts, from paper sketches to final mark.", "Storefront and window design for a Saudi fashion brand in Khobar."],
  "makkah.hospitality": ["تصوير بهو فندق في مكة المكرمة لحملة ضيافة.", "جناح فندقي بإطلالة على المدينة عند المساء لإعلانات الحجز.", "خطة محتوى شهرية لمجموعة فنادق: منشورات وإعلانات وحملات مواسم."],
  "abha.trails": ["Misty mountains and the cable car in Abha for a tourism campaign.", "Drone shot of Rijal Almaa heritage village at golden hour.", "Filming hikers on an Asir mountain trail as the fog rolls in."],
  "madinah.dates": ["تصوير علب هدايا تمر العجوة لمتجر إلكتروني في المدينة المنورة.", "إعلان سناب شات: فتح علبة تمور فاخرة مع دلة القهوة.", "تجهيز الطلبات لمتجر تمور إلكتروني: من التغليف إلى التوصيل."],
};

/** Open client briefs so agencies see a live request feed (source "demo", removable with the demo data). */
export const DEMO_REQUESTS: { country: string; city: string; clientName: string; businessName: string; businessType: string; services: string[]; platforms: string[]; budget: [number, number]; timeline: string; description: string }[] = [
  { country: "sa", city: "riyadh", clientName: "فهد", businessName: "مقهى الروشن", businessType: "restaurant_cafe", services: ["smm_management", "ads_snapchat"], platforms: ["snapchat", "instagram"], budget: [3000, 6000], timeline: "this_month", description: "نفتتح فرعًا جديدًا في شمال الرياض ونحتاج إدارة حسابات وإعلانات سناب شات لمدة ثلاثة أشهر، مع تقرير أسبوعي." },
  { country: "sa", city: "jeddah", clientName: "Sara", businessName: "Red Sea Homes", businessType: "real_estate", services: ["ads_google", "ads_meta", "web_design"], platforms: ["google", "instagram"], budget: [8000, 15000], timeline: "asap", description: "Real estate developer in Jeddah looking for a lead-generation campaign and a landing page for a new residential project." },
  { country: "sa", city: "dammam", clientName: "خالد", businessName: "مصنع الشرق للمعدات", businessType: "manufacturing", services: ["video_production", "ads_linkedin"], platforms: ["linkedin", "youtube"], budget: [10000, 20000], timeline: "within_3_months", description: "نحتاج فيلمًا تعريفيًا للمصنع وحملة لينكدإن للوصول إلى مديري المشتريات في الخليج." },
  { country: "sa", city: "madinah", clientName: "Abdullah", businessName: "Ajwa Gifts", businessType: "ecommerce", services: ["ecommerce_setup", "ads_tiktok", "photography"], platforms: ["tiktok", "snapchat"], budget: [4000, 9000], timeline: "this_month", description: "Online dates and gifts store ahead of the season: product photos, store setup and TikTok ads." },
  { country: "sa", city: "abha", clientName: "نورة", businessName: "نزل السودة", businessType: "tourism_hospitality", services: ["video_production", "smm_content"], platforms: ["instagram", "youtube"], budget: [5000, 10000], timeline: "within_3_months", description: "نزل سياحي في السودة يريد محتوى فيديو وصور لموسم الصيف وحسابًا نشطًا على إنستغرام." },
  { country: "jo", city: "amman", clientName: "Lina", businessName: "Nour Clinic", businessType: "clinic_health", services: ["smm_management", "ads_meta"], platforms: ["instagram", "facebook"], budget: [300, 600], timeline: "this_month", description: "Dermatology clinic in Amman: account management, doctor-led reels and Meta ads for bookings." },
];
